[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn Core.wsgi --bind 0.0.0.0:$PORT --log-file -"
healthcheckPath = "/admin/"
restartPolicyType = "on_failure"
