# Generated by Django 5.2.12 on 2026-03-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=15),
        ),
        migrations.AddField(
            model_name='citas',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='citas',
            name='tipo',
            field=models.CharField(choices=[('civil', 'Derecho Civil'), ('comercial', 'Derecho Comercial'), ('familia', 'Derecho de Familia'), ('inmobiliario', 'Derecho Inmobiliario'), ('laboral', 'Derecho Laboral'), ('penal', 'Derecho Penal')], default='civil', max_length=20),
        ),
        migrations.AlterField(
            model_name='citas',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
