# Generated by Django 5.2.12 on 2026-03-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_citas_estado_citas_google_event_id_citas_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
